//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Io.Outputs
{
	public partial interface IAlias {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class DAGArrayOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGBooleanOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGFileOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGFolderOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGGenericOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGIntegerOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGJSONObjectOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGLinkedOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGNumberOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGPathOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
	public partial class DAGStringOutputAlias: PollinationSDK.Interface.Io.Outputs.IAlias {}
}
