//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Base
{
	public partial interface IMetadata {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class License: PollinationSDK.Interface.Base.IMetadata {}
	public partial class Maintainer: PollinationSDK.Interface.Base.IMetadata {}
	public partial class MetaData: PollinationSDK.Interface.Base.IMetadata {}
}
