//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Plugin
{
	public partial interface IFunction {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class Function: PollinationSDK.Interface.Plugin.IFunction {}
}
