//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Server.Rest.User
{
	public partial interface IDto {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class UserCreate: PollinationSDK.Interface.Server.Rest.User.IDto {}
	public partial class UserPrivate: PollinationSDK.Interface.Server.Rest.User.IDto {}
	public partial class UserUpdate: PollinationSDK.Interface.Server.Rest.User.IDto {}
}
