//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Server.Rest.Repositories
{
	public partial interface IDto {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class Repository: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryAccessPolicy: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryAccessPolicyList: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryCreate: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryList: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryPackage: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryPolicySubject: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryUpdate: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
	public partial class RepositoryUserPermissions: PollinationSDK.Interface.Server.Rest.Repositories.IDto {}
}
