//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Server.Rest.Teams
{
	public partial interface IDto {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class Team: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
	public partial class TeamCreate: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
	public partial class TeamList: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
	public partial class TeamMember: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
	public partial class TeamMemberList: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
	public partial class TeamUpdate: PollinationSDK.Interface.Server.Rest.Teams.IDto {}
}
