/* 
 * Pollination Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.28
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PollinationSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace PollinationSDK.Test
{
    /// <summary>
    ///  Class for testing ProjectAccessPolicyDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectAccessPolicyDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProjectAccessPolicyDto
        //private ProjectAccessPolicyDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectAccessPolicyDto
            //instance = new ProjectAccessPolicyDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectAccessPolicyDto
        /// </summary>
        [Test]
        public void ProjectAccessPolicyDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProjectAccessPolicyDto
            //Assert.IsInstanceOf(typeof(ProjectAccessPolicyDto), instance);
        }


        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Test]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

    }

}
