/* 
 * Pollination Server
 *
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: info@pollination.cloud
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PollinationSDK.Api;
using PollinationSDK.Model;
using PollinationSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PollinationSDK.Test
{
    /// <summary>
    ///  Class for testing RepositoryIndex
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepositoryIndexTests
    {
        // TODO uncomment below to declare an instance variable for RepositoryIndex
        //private RepositoryIndex instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RepositoryIndex
            //instance = new RepositoryIndex();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepositoryIndex
        /// </summary>
        [Test]
        public void RepositoryIndexInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RepositoryIndex
            //Assert.IsInstanceOf(typeof(RepositoryIndex), instance);
        }


        /// <summary>
        /// Test the property 'Generated'
        /// </summary>
        [Test]
        public void GeneratedTest()
        {
            // TODO unit test for the property 'Generated'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Test]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'Recipe'
        /// </summary>
        [Test]
        public void RecipeTest()
        {
            // TODO unit test for the property 'Recipe'
        }

    }

}
