/* 
 * Pollination Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.8
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PollinationSDK.Api;
using PollinationSDK.Model;
using PollinationSDK.Client;
using PollinationSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace PollinationSDK.Test
{
    /// <summary>
    ///  Class for testing SimulationOutputSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimulationOutputSourceTests
    {
        // TODO uncomment below to declare an instance variable for SimulationOutputSource
        //private SimulationOutputSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimulationOutputSource
            //instance = new SimulationOutputSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimulationOutputSource
        /// </summary>
        [Test]
        public void SimulationOutputSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SimulationOutputSource
            //Assert.IsInstanceOf(typeof(SimulationOutputSource), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Simulation'
        /// </summary>
        [Test]
        public void SimulationTest()
        {
            // TODO unit test for the property 'Simulation'
        }
        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Test]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
