/* 
 * Pollination Server
 *
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: info@pollination.cloud
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PollinationSDK.Api;
using PollinationSDK.Model;
using PollinationSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PollinationSDK.Test
{
    /// <summary>
    ///  Class for testing TaskStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskStatusTests
    {
        // TODO uncomment below to declare an instance variable for TaskStatus
        //private TaskStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskStatus
            //instance = new TaskStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskStatus
        /// </summary>
        [Test]
        public void TaskStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TaskStatus
            //Assert.IsInstanceOf(typeof(TaskStatus), instance);
        }


        /// <summary>
        /// Test the property 'BoundaryId'
        /// </summary>
        [Test]
        public void BoundaryIdTest()
        {
            // TODO unit test for the property 'BoundaryId'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Test]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }
        /// <summary>
        /// Test the property 'FinishedAt'
        /// </summary>
        [Test]
        public void FinishedAtTest()
        {
            // TODO unit test for the property 'FinishedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OutboundTasks'
        /// </summary>
        [Test]
        public void OutboundTasksTest()
        {
            // TODO unit test for the property 'OutboundTasks'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Test]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TemplateRef'
        /// </summary>
        [Test]
        public void TemplateRefTest()
        {
            // TODO unit test for the property 'TemplateRef'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
