/* 
 * Pollination Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.28
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PollinationSDK;

using System.Reflection;
using Newtonsoft.Json;

namespace PollinationSDK.Test
{
    /// <summary>
    ///  Class for testing UpdateAccepted
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAcceptedTests
    {
        // TODO uncomment below to declare an instance variable for UpdateAccepted
        //private UpdateAccepted instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateAccepted
            //instance = new UpdateAccepted();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateAccepted
        /// </summary>
        [Test]
        public void UpdateAcceptedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateAccepted
            //Assert.IsInstanceOf(typeof(UpdateAccepted), instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
