//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace PollinationSDK.Interface.Modules.Projects.Dto
{
	public partial interface IProject {}
}

//Classes implemented this interface:
namespace PollinationSDK
{
	public partial class Project: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectAccessPolicy: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectAccessPolicyList: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectCreate: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectDailyUsage: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectList: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectPolicySubject: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectRecipeFilter: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectRecipeFilterList: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectUpdate: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectUsage: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
	public partial class ProjectUserPermissions: PollinationSDK.Interface.Modules.Projects.Dto.IProject {}
}
